### PR TITLE
First version

### PR DESCRIPTION
**Pull request by Soresu**

### CODE REVIEW

**Comment by jQueryBase64MyAss** [comment]
Thank you I will review this asap!

**Comment by ChewyMoon** [comment]
`a++` and `++a` are not the same thing. 

The first form is a prefix increment operation. The result of the operation is the value of the operand after it has been incremented.
The second form is a postfix increment operation. The result of the operation is the value of the operand before it has been incremented.

Lets say that `a` = `10`

If we write this to the console `a++`, you'll get 11, while if you write `++a` you'll get 10, but the value will be 11 after the statement has ended.

**Comment by Soresu** [comment]
it was bad composition.
"All of these command do the same thing"
It should be: "All of these command increment the value by one"
The next lines about the prefix and postfix.

**Comment by jQueryBase64MyAss** [comment]
Thanks!

**Comment by Everesty** [comment]
Welp, "If we write this to the console a++, you'll get 11, while if you write ++a you'll get 10, but the value will be 11 after the statement has ended." Incorrect, switch them.

`a++` will result in 10 in the console (since that's postfix). `++a` will result in 11 in the console (since that's prefix).

Reference: https://msdn.microsoft.com/en-us/library/36x43w8w.aspx

**Pull request closed without merging**
